development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: survivalguide_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: survivalguide_test
  pool: 5

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
